services:      
    feneck91.introduciator.helper:
        class: feneck91\introduciator\helper\introduciator_helper
        arguments:
            - %core.table_prefix%
            - %core.root_path%
            - %core.php_ext%
            - @user
            - @dbal.conn
            - @config
            - @auth
            - @controller.helper


    feneck91.introduciator.explain:
        class: feneck91\introduciator\controller\introduciator_explain
        arguments:
            - @config
            - @auth
            - @template
            - @user

    feneck91.introduciator.listener:
        class: feneck91\introduciator\event\introduciator_listener
        arguments:
            - @user
            - @template
            - @template_context
            - @service_container
        tags:
            - { name: event.listener }
