services:      
    feneck91.introduciator.helper:
        class: feneck91\introduciator\helper\introduciator_helper
        arguments:
            - %core.table_prefix%
            - %core.root_path%
            - %core.php_ext%
            - @user
            - @dbal.conn
            - @config
            - @auth
