services:      
    feneck91.introduciator.main_controller:
        class: feneck91\introduciator\controller\
        arguments:
            - @config
            - @request
            - @pagination
            - @dbal.conn
            - @auth
            - @template
            - @user
            - @controller.helper
            - %core.root_path%
            - %core.php_ext%
    
   feneck91.introduciator.listener:
        class: feneck91\introduciator\event\listener
        tags:
            - { name: event.listener }